source 'https://rubygems.org'

gemspec

group :development do
  gem 'pry', require: false
  gem 'rubocop-performance', require: false
  gem 'sorbet', require: false
  gem "tapioca", require: false
end

group :test do
  gem 'qd3v-testing-core', path: '../qd3v-testing-core'
  gem 'benchmark', require: false
end
