source 'https://rubygems.org'

gemspec

gem 'qd3v-core', path: '../qd3v-core'
gem 'qd3v-testing-core', path: '../qd3v-testing-core'

group :development do
  gem 'pry', require: false
  gem 'rubocop-performance', require: false
  gem 'sorbet', require: false
  gem "tapioca", require: false
end

group :test do
end
